### ISSUE TITLE
restart_gitlab_runner job fail on CentOS 7 Could not find the requested service gitlab-runner: host

### ISSUE THREAD

**Issue by avolkov** [riemers/ansible-gitlab-runner#106]
Hello,

I'm running riemers.gitlab-runner 1.6.1 playbook with the following parameters

 
```
 - role: riemers.gitlab-runner
     gitlab_runner_coordinator_url: --skip--
     gitlab_runner_registration_token: --skip--
     gitlab_runner_package_name: gitlab-runner
     gitlab_runner_concurrent: 1
     gitlab_runner_runners:
       - name: test-run
         concurrent_specific: 1
         tags: [tr-tag]
         run_untagged: false
         locked: true
     become: true
```

On initial run everythings seems fine but on subsequent runs I'm getting this failure

```
RUNNING HANDLER [riemers.gitlab-runner : restart_gitlab_runner] *************************************************************************************************************************************************************************************************************** fatal: [test-playbook]: FAILED! => {"changed": false, "msg": "Could not find the requested service gitlab-runner: host"}
```

**Comment by riemers** [comment]
1.6.1 is out some time, i would assume if it was broken more would have talked by now. But we can always check if other people have the same issue.  I only have travis to look upon at the moment

**Comment by avolkov** [comment]
Sorry, i looked at my configuration again and I had role statement repeated.

I'm running some more test but it looks like my error. sorry.

**Comment by avolkov** [comment]
Confirmed. I had the following config that cause problems

```
 - role: riemers.gitlab-runner
 - role: riemers.gitlab-runner
     gitlab_runner_coordinator_url: --skip--
     gitlab_runner_registration_token: --skip--
     gitlab_runner_package_name: gitlab-runner
     gitlab_runner_concurrent: 1
     gitlab_runner_runners:
       - name: test-run
         concurrent_specific: 1
         tags: [tr-tag]
         run_untagged: false
         locked: true
     become: true
```
