### ISSUE TITLE
Dubble runners.machine config with docker+machine

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [riemers/ansible-gitlab-runner#121]
Hello,

I'm using your role (master branch) for installing my gitlab-runner with docker+machine on gcs.
I ran into the issue that runners.machine already exists in my configuration.

After checking the temp config file i do see a double runners.machine entry:

```
cat gitlab-runner.1.1kG9jL
  name = "gitlab-runner01"
  limit = 0
  output_limit = 4096
  url = "<url>"
  environment = []
  token = "<token>"
  executor = "docker+machine"
  [runners.machine]
  [runners.machine]
    MachineOptions = ["google-project=<id>", "google-machine-type=n1-standard-1", "google-machine-image=https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-minimal-1804-lts", "google-tags=gitlab-ci-slave", "google-preemptible=true", "google-zone=europe-west1-d"]
    MachineName = "auto-scale-runner-%s"
    MachineDriver = "google"
    MaxBuilds = 100
    IdleTime = 3600
    IdleCount = 1
  [runners.custom_build_dir]
  [runners.cache]
  [runners.docker]
    image = "ubuntu:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
```

Found following tasks that creates the runners.machine section.
```
- name: Set runner executor section
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*\[runners\.{{ gitlab_runner.executor|default("shell") }}\]'
    line: '  [runners.{{ gitlab_runner.executor|replace("docker+machine","machine")|default("shell") }}]'
    state: "{{ 'absent' if (gitlab_runner.executor|default('shell')) == 'shell' else 'present' }}"
    insertafter: '^\s*executor ='
    backrefs: no
  check_mode: no
  notify:
  - restart_gitlab_runner
  - restart_gitlab_runner_macos
```

This can be skipped if the executor is docker+machine as you loop over the extra_configs in the vars and insert a second runners.machine.

```gitlab_runner_runners:
  - name: 'gitlab-runner01'
    state: present
    # token is an optional override to the global gitlab_runner_registration_token
    executor: 'docker+machine'
    # Maximum number of jobs to run concurrently on this specific runner.
    docker_image: 'ubuntu:latest'
    docker_volumes: ["/var/run/docker.sock:/var/run/docker.sock","/cache"]
    docker_privileged: true
    tags:
      - docker
      - dind
    # Indicates whether this runner can pick jobs without tags.
    run_untagged: true
    locked: false
    extra_configs:
      runners.machine:
        IdleCount: 1
        IdleTime: 3600
        MaxBuilds: 100
        MachineDriver: 'google'
        MachineName: 'auto-scale-runner-%s'
        MachineOptions: ["google-project={{ gcloud_project_id }}",
                          "google-machine-type=n1-standard-1",
                          "google-machine-image=https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-minimal-1804-lts",
                          "google-tags=gitlab-ci-slave",
                          "google-preemptible=true",
                          "google-zone=europe-west1-d"]
```

After i added the when statement to the task, my problem has been solved and deploy of the runner was successful.
```
- name: Set runner executor section
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*\[runners\.{{ gitlab_runner.executor|default("shell") }}\]'
    line: '  [runners.{{ gitlab_runner.executor|replace("docker+machine","machine")|default("shell") }}]'
    state: "{{ 'absent' if (gitlab_runner.executor|default('shell')) == 'shell' else 'present' }}"
    insertafter: '^\s*executor ='
    backrefs: no
  when: gitlab_runner.executor != "docker+machine"
  check_mode: no
  notify:
  - restart_gitlab_runner
  - restart_gitlab_runner_macos
```
