### ISSUE TITLE
Offpeak option is deprecated and will be removed in version 14.

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [riemers/ansible-gitlab-runner#139]
Hello,

Just wondering how i can configure a subsection under runners.machine?
The current offpeak option will be removed with gitlabrunner version 14.
The new solution is using the runners.machine.autoscaling option: https://docs.gitlab.com/runner/configuration/autoscale.html#autoscaling-periods-configuration

Current config:
```
extra_configs:
      runners.machine:
        IdleCount: 1
        IdleTime: 1800
        OffPeakPeriods: ["* * 0-7,18-23 * * mon-fri *", "* * * * * sat,sun *"]
        OffPeakIdleCount: 0
        OffPeakIdleTime: 600
        MachineDriver: 'google'
```

New config:

```
extra_configs:
      runners.machine:
        IdleCount: 1
        IdleTime: 1800
        MachineDriver: 'google'
        runners.machine.autoscaling:
          Periods: ["* * 0-7,18-23 * * mon-fri *","* * * * * sat,sun *"]
          IdleCount: 0
          IdleTime: 600
```
output with the new section:

```
[runners.machine]
    IdleTime = 1800
    IdleCount = 1
    MachineDriver = "google"
    MachineName = "auto-scale-runner-%s"
    runners.machine.autoscaling = {"Periods": ["* * 0-7,18-23 * * mon-fri *", "* * * * * sat,sun *"], "IdleCount": 0, "IdleTime": 600}
```

should be:

```
[runners.machine]
    IdleTime = 1800
    IdleCount = 1
    MachineDriver = "google"
    MachineName = "auto-scale-runner-%s"
    [[runners.machine.autoscaling]]
      Periods = ["* * 0-7,18-23 * * mon-fri *", "* * * * * sat,sun *"]
      IdleCount = 0
      IdleTime = 600
```

Is there an issue with my config in Ansible or is this not supported yet?
