### ISSUE TITLE
Error on 'Assemble new config.toml' FATAL: Failed to verify runners

### ISSUE THREAD

**Issue by avolkov** [riemers/ansible-gitlab-runner#153]
This error occurs when I run ansible task on an existing runner configuration, that's been set up at the previous runner invocation. This error happens in version 1.6.22 but also been observed in older versions

Error message

```
TASK [riemers.gitlab-runner : Assemble new config.toml] ***************************************************************************************************************************************************************************
fatal: [machine-dev]: FAILED! => {"changed": false, "msg": "failed to validate: rc:1 error:Runtime platform                                  \u001b[0;m  arch\u001b[0;m=amd64 os\u001b[0;m=linux pid\u001b[0;m=22171 revision\u001b[0;m=8fa89735 version\u001b[0;m=13.6.0\nRunning in system-mode.                           \u001b[0;m \n                                                  \u001b[0;m \n\u001b[31;1mERROR: Verifying runner... is removed             \u001b[0;m  \u001b[31;1mrunner\u001b[0;m=sJ_y4-2a\n\u001b[31;1mFATAL: Failed to verify runners                   \u001b[0;m \n"}
```

Offending section in riemers.gitlab-runner/tasks/cofnig-runners.yml line 27-35

```
- name: Assemble new config.toml (systems mode)
  assemble:
    src: "{{ temp_runner_config_dir.path }}"
    dest: "{{ gitlab_runner_config_file }}"
    delimiter: '[[runners]]\n'
    backup: yes
    validate: "{{ gitlab_runner_executable }} verify -c %s"
    mode: 0600
  become: "{{ gitlab_runner_system_mode }}"
```

When I ran the same command manually for  gitlab-runner-13.6.0-1.x86_64 on CentOS 7.x

```
[root@machine-dev gitlab-runner]# /bin/gitlab-runner verify -c config.toml.19881.2020-06-05\@16\:42\:44~ 
Runtime platform                                    arch=amd64 os=linux pid=22364 revision=8fa89735 version=13.6.0
Running in system-mode.                            
                                                   
Verifying runner... is alive                        runner=sJ_y4-2a
```

Runner configuration

```
- hosts: machine-dev
  roles:
    - role: riemers.gitlab-runner
      gitlab_runner_coordinator_url: https://internal.internal/
      gitlab_runner_registration_token: ---snip--
      gitlab_runner_package_name: gitlab-runner
      gitlab_runner_system_mode: True
      gitlab_runner_concurrent: 1
      gitlab_runner_runners:
        - name: machine-dev
          executor: shell
          concurrent_specific: '1'
          tags:
            - machine-dev
          run_untagged: false
          locked: 'true'
      become: true
```

Everything seems to be working, it's just this error happens whenever  I re-run the task for this runner configuration.
