### ISSUE TITLE
concurrent is always set to 1

### ISSUE THREAD

**Issue by szEvEz** [riemers/ansible-gitlab-runner#191]
Setting the var `gitlab_runner_concurrent` does not seem to have effect on the final config.toml.

playbook

```yml
- hosts: all
  become: true
  vars_files:
    - vars.yaml
  roles:
    - riemers.gitlab-runner
```

vars file

```yml
gitlab_runner_concurrent: 5
gitlab_runner_coordinator_url: https://gitlab.com
gitlab_runner_session_server_session_timeout: 1800
gitlab_runner_container_image: gitlab/gitlab-runner
gitlab_runner_container_tag: v14.0.1
gitlab_runner_container_name: gitlab-runner
gitlab_runner_container_restart_policy: unless-stopped
gitlab_runner_container_install: true
gitlab_runner_runners:
  - name: 'runnername'
    executor: docker
    docker_image: 'docker'
    docker_volumes:
      - "/cache"
    docker_privileged: true
    env_vars: ["DOCKER_DRIVER=overlay2"]
    extra_configs:
      runners.docker:
        disable_cache: false
        pull_policy: ["if-not-present"]
        shm_size: 0
        disable_entrypoint_overwrite: false
        oom_kill_disable: false
```

final config toml

```sh
root@myserver:/srv/gitlab-runner# cat config.toml 

concurrent = 1
...
```

Any ideas why?

**Comment by cuyk** [comment]
works for me

**Comment by cadu-leite** [comment]
Actually
for me , nothing in `vars` works
it ignore completly even the runnner setting
```yaml
gitlab_runner_concurrent: 3
gitlab_runner_session_server_session_timeout: 1800
gitlab_runner_container_image: gitlab/gitlab-runner
gitlab_runner_container_tag: v14.0.1
gitlab_runner_container_name: gitlab-runner
gitlab_runner_container_restart_policy: unless-stopped
gitlab_runner_container_install: true
gitlab_runner_coordinator_url: 'xxxxxxxxxxxxx'
gitlab_runner_registration_token: 'xxxxxxxxxxxxx'
gitlab_runner:
  - name: 'DockRun1'
    executor: docker
    docker_image: 'alpine'
    tags:
      - docker-runner
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    extra_configs:
      runners.docker:
        memory: 512m
      runners.docker.sysctls:
        net.ipv4.ip_forward: "1"
  - name: 'DockRun2'
    executor: docker
    docker_image: 'alpine'
    tags:
      - docker-runner
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    extra_configs:
      runners.docker:
        memory: 512m
      runners.docker.sysctls:
        net.ipv4.ip_forward: "1"
```
