### ISSUE TITLE
conflicting action statements: hosts, vars_files

### ISSUE THREAD

**Issue by sezanzeb** [riemers/ansible-gitlab-runner#203]
Using the proposed way to configure this fails

```yml
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - { role: riemers.gitlab-runner }
```

```
TASK [Run the GitLab CI runner setup] ******************************************
ERROR! conflicting action statements: hosts, vars_files

The error appears to be in '...': line 14, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: all
  ^ here
```
