### ISSUE TITLE
dict object' has no attribute 'virtualbox_base_snapshot' error

### ISSUE THREAD

**Issue by JMLX42** [riemers/ansible-gitlab-runner#239]
Hello,

there is an inconsistency on the default value of the `gitlab_runner.virtualbox_base_snapshot` runner prop.

https://github.com/riemers/ansible-gitlab-runner/blob/94083260222b7f0880ccc21d716bc0abf947d866/tasks/update-config-runner.yml#L727

```yml
- name:  "{{ runn_name_prefix }} Set virtualbox base snapshot option"
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*base_snapshot ='
    line: '    base_snapshot = {{ gitlab_runner.virtualbox_base_snapshot | to_json }}'
    state: "{{ 'present' if gitlab_runner.virtualbox_base_snapshot is defined else 'absent' }}"
    insertafter: '^\s*\[runners\.virtualbox\]'
    backrefs: no
  check_mode: no
  when: gitlab_runner.executor == 'virtualbox' and gitlab_runner.virtualbox_base_name is defined
  notify:
  - restart_gitlab_runner
  - restart_gitlab_runner_macos
```

The `state` checks if `gitlab_runner.virtualbox_base_snapshot` is defined or not. But if it is undefined, the `line` will fail to evaluate `gitlab_runner.virtualbox_base_snapshot`:

```
TASK [riemers.gitlab-runner : conf[3/3]: runner[2/2]: Set virtualbox base snapshot option] ***
fatal: [build-linux]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'virtualbox_base_snapshot'\n\nThe error appears to be in '/vagrant/provisioning/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 723, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name:  \"{{ runn_name_prefix }} Set virtualbox base snapshot option\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

The important part of the error message:

```
The error was: 'dict object' has no attribute 'virtualbox_base_snapshot'

The error appears to be in '/vagrant/provisioning/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 723, column 3, but may
be elsewhere in the file depending on the exact syntax problem
```

In the rest of the code, `` has the `""` (empty string) default value if missing:

https://github.com/riemers/ansible-gitlab-runner/blob/ef969a5df10c59dbca9c5f8fd57c59a86716d9bf/tasks/register-runner.yml#L109

The same problems exists for `gitlab_runner.virtualbox_base_folder`.

In both cases, the solution is to add `| default("")`:

```yml
- name:  "{{ runn_name_prefix }} Set virtualbox base snapshot option"
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*base_snapshot ='
    line: '    base_snapshot = {{ gitlab_runner.virtualbox_base_snapshot | default("") | to_json }}'
    state: "{{ 'present' if gitlab_runner.virtualbox_base_snapshot is defined else 'absent' }}"
    insertafter: '^\s*\[runners\.virtualbox\]'
    backrefs: no
  check_mode: no
  when: gitlab_runner.executor == 'virtualbox' and gitlab_runner.virtualbox_base_name is defined
  notify:
  - restart_gitlab_runner
  - restart_gitlab_runner_macos
```

**Comment by riemers** [comment]
Could you bump that into a PR?
________________________________
Van: Jean-Marc Le Roux ***@***.***>
Verzonden: Wednesday, May 11, 2022 12:38:43 PM
Aan: riemers/ansible-gitlab-runner ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [riemers/ansible-gitlab-runner] dict object' has no attribute 'virtualbox_base_snapshot' error (Issue #239)


Hello,

there is an inconsistency on the default value of the gitlab_runner.virtualbox_base_snapshot runner prop.

https://github.com/riemers/ansible-gitlab-runner/blob/94083260222b7f0880ccc21d716bc0abf947d866/tasks/update-config-runner.yml#L727

- name:  "{{ runn_name_prefix }} Set virtualbox base snapshot option"
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*base_snapshot ='
    line: '    base_snapshot = {{ gitlab_runner.virtualbox_base_snapshot | to_json }}'
    state: "{{ 'present' if gitlab_runner.virtualbox_base_snapshot is defined else 'absent' }}"
    insertafter: '^\s*\[runners\.virtualbox\]'
    backrefs: no
  check_mode: no
  when: gitlab_runner.executor == 'virtualbox' and gitlab_runner.virtualbox_base_name is defined
  notify:
  - restart_gitlab_runner
  - restart_gitlab_runner_macos

The state checks if gitlab_runner.virtualbox_base_snapshot is defined or not. But if it is undefined, the line will fail to evaluate gitlab_runner.virtualbox_base_snapshot:

TASK [riemers.gitlab-runner : conf[3/3]: runner[2/2]: Set virtualbox base snapshot option] ***
fatal: [build-linux]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'virtualbox_base_snapshot'\n\nThe error appears to be in '/vagrant/provisioning/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 723, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name:  \"{{ runn_name_prefix }} Set virtualbox base snapshot option\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}


The important part of the error message:

The error was: 'dict object' has no attribute 'virtualbox_base_snapshot'

The error appears to be in '/vagrant/provisioning/roles/riemers.gitlab-runner/tasks/update-config-runner.yml': line 723, column 3, but may
be elsewhere in the file depending on the exact syntax problem


In the rest of the code, `` has the "" (empty string) default value if missing:

https://github.com/riemers/ansible-gitlab-runner/blob/ef969a5df10c59dbca9c5f8fd57c59a86716d9bf/tasks/register-runner.yml#L109

The same problems exists for gitlab_runner.virtualbox_base_folder.

In both cases, the solution is to add | default(""):

- name:  "{{ runn_name_prefix }} Set virtualbox base snapshot option"
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*base_snapshot ='
    line: '    base_snapshot = {{ gitlab_runner.virtualbox_base_snapshot | default("") | to_json }}'
    state: "{{ 'present' if gitlab_runner.virtualbox_base_snapshot is defined else 'absent' }}"
    insertafter: '^\s*\[runners\.virtualbox\]'
    backrefs: no
  check_mode: no
  when: gitlab_runner.executor == 'virtualbox' and gitlab_runner.virtualbox_base_name is defined
  notify:
  - restart_gitlab_runner
  - restart_gitlab_runner_macos

**Comment by JMLX42** [comment]
> Could you bump that into a PR?

@riemers yes I'll try to do it. Not before a few week though.

Got a similar today when adding this:

```yml
    extra_configs:
      runners.ssh:
        disable_strict_host_key_checking: true
```

that happened to generate this:

```toml
[runners.ssh]
    "disable_strict_host_key_checking" = true
```

@riemers why the extra double quotes? I would expect:

```toml
[runners.ssh]
    disable_strict_host_key_checking = true
```

IMHO that will break with the exact problem than this issue when we add "native" support for `disable_strict_host_key_checking` (which might be very soon, cf https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28192 and https://docs.gitlab.com/runner/executors/ssh.html#security)
