### ISSUE TITLE
force_accept_gitlab_server_self_signed undefined variable errors

### ISSUE THREAD

**Issue by g0rgamesh** [riemers/ansible-gitlab-runner#272]
When using `force_accept_gitlab_server_self_signed` I got theses undefined variable errors for:
- gitlab_server_ip
- tls_ca_file

**Comment by guenhter** [comment]
This task is run when `force_accept_gitlab_server_self_signed` is set:

```yaml

- name: Accept gitlab server self signed cert as valid CA
  shell: "openssl s_client -connect {{gitlab_server_ip}}:443 -showcerts </dev/null 2>/dev/null | sed -e '/-----BEGIN/,/-----END/!d' | tee {{tls_ca_file}} >/dev/null"
  when: force_accept_gitlab_server_self_signed
```

Obviously it needs the two variables you just described. Without the presence of the two variables  `gitlab_server_ip` and `tls_ca_file` the task won't work. Defaulting the two variables to an empty value doesn't seem a good choice, does it?
