### ISSUE TITLE
Please add support install using proxy (squid)

### ISSUE THREAD

**Issue by patsevanton** [riemers/ansible-gitlab-runner#28]
HI!
I try Install gitlab using this playbook using squid in Corporate NetWork.
But dont work
Please add support install using proxy (squid)
Thanks!

**Comment by riemers** [comment]
Do you have examples of playbooks that have proxy support? Since i have not seen one and i think you should not want to have that either. You either download the role locally or you download it from galaxy. If ansible tries to download it from galaxy or somewhere else it is not a problem of the my role.

**Comment by patsevanton** [comment]
I mean install gitlab-runner using proxy(squid) - not install playbook from galaxy

**Comment by riemers** [comment]
i don't get it, you want to download the gitlab runner through the proxy? have you tried setting your HTTP_PROXY and HTTPS_PROXY environments on the commandline? Assuming it is not a kerberos authenticated squid.

**Comment by patsevanton** [comment]
I try run

```
- hosts: gitlab-runner
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: riemers.gitlab-runner }
  vars:
    environment:
      http_proxy: 'http://192.168.88.249:3128'
      https_proxy: 'http://192.168.88.249:3128'
```

playbook dont use proxy
