### ISSUE TITLE
"The conditional check ''Executor' in json_item' failed

### ISSUE THREAD

**Issue by dcardellino** [riemers/ansible-gitlab-runner#284]
With v2.0.2 I get the following error, when setting up a docker runner:

```
TASK [riemers.gitlab-runner : Create list of configured runners] *****************************************************************************************************************************************************
skipping: [gitlab-runner] => (item={'arch': 'amd64', 'level': 'info', 'msg': 'Runtime platform', 'os': 'linux', 'pid': 7, 'revision': '85586bd1', 'time': '2023-10-06T10:57:01Z', 'version': '16.0.2'})
skipping: [gitlab-runner] => (item={'ConfigFile': '/etc/gitlab-runner/config.toml', 'level': 'info', 'msg': 'Listing configured runners', 'time': '2023-10-06T10:57:01Z'})
fatal: [gitlab-runner]: FAILED! => {"msg": "The conditional check ''Executor' in json_item' failed. The error was: An unhandled exception occurred while templating '{{ item | from_json }}'. Error was a <class 'json.decoder.JSONDecodeError'>, original message: Expecting value: line 1 column 1 (char 0)\n\nThe error appears to be in '/etc/ansible/vendor/riemers.gitlab-runner/tasks/list-configured-runners-container.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create list of configured runners\n  ^ here\n"}
```

**Comment by guenhter** [comment]
This seems very similar

https://github.com/riemers/ansible-gitlab-runner/issues/282

**Comment by dcardellino** [comment]
Looks fine with the fix. Ran without problems.

**Comment by guenhter** [comment]
@guenhter PR is merged. 

Either you use the latest version via `master` branch name or you can ask @riemers to create a new tag to have it available via Ansible Galaxy.

**Comment by kakawait** [comment]
@guenhter I'm facing similar issue even with `2.0.3`

Here my `roles/requirements.yml`

```yml
- name: riemers.ansible-gitlab-runner
  src: https://github.com/riemers/ansible-gitlab-runner/archive/v2.0.3.tar.gz
```

I've also tried without the `src`, but I've added `src` after to be sure that I'm correctly fetching `2.0.3`

```bash
[root@vanakindsy gitlab-ansible-playbook]# ansible-galaxy install -r roles/requirements.yml --force
Starting galaxy role install process
- changing role riemers.ansible-gitlab-runner from v2.0.3 to unspecified
- downloading role from https://github.com/riemers/ansible-gitlab-runner/archive/v2.0.3.tar.gz
- extracting riemers.ansible-gitlab-runner to /root/.ansible/roles/riemers.ansible-gitlab-runner
- riemers.ansible-gitlab-runner was installed successfully
```

and I've 

```
TASK [riemers.ansible-gitlab-runner : conf[2/2]: runner[1/1]: Set additional services] *****************************************************************************************************
fatal: [anakin.dsone.3ds.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.\n\nThe error appears to be in '/root/.ansible/roles/riemers.ansible-gitlab-runner/tasks/update-config-runner.yml': line 402, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#### [[runners.docker.services]] section ####\n- name:  \"{{ runn_name_prefix }} Set additional services\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

with following usage

```yml
- import_role:
     name: riemers.gitlab-runner
```

and variables

```yml
gitlab_runner_registration_token: THE_TOKEN
gitlab_runner_coordinator_url: https://gitlab.blaba/ci
gitlab_runner_windows_service_user: "domain\\user"
gitlab_runner_windows_service_password: password
# A list of runners to register and configure
gitlab_runner_runners:
    # The identifier of the runner.
  - name: "{{ inventory_hostname }} - shell"
    # set to 'absent' if you want to delete the runner. Defaults to 'present'.
    state: present
    # The executor used by the runner.
    executor: 'shell'
    shell: "{{ (ansible_system == 'Linux') | ternary('bash', 'powershell') }}"
    # Set maximum build log size in kilobytes.
    output_limit: 4096
    # Maximum number of jobs to run concurrently on this specific runner.
    # Defaults to 0, simply means don't limit.
    concurrent_specific: '5'
    # The tags assigned to the runner.
    tags:
      - "{{ inventory_hostname }}"
      - "shell"
      - "{{ (ansible_system == 'Linux') | ternary('linux', 'windows') }}"
    # Indicates whether this runner can pick jobs without tags.
    run_untagged: false
    # Docker privileged mode
    docker_privileged: false
    # Runner Locked. When a runner is locked, it cannot be assigned to other projects
    locked: 'false'
    # Custom environment variables injected to registration command
    env_vars: []
```

However it works if I'm downgrading to `v1.6.50`

May I missed something?
