### ISSUE TITLE
"No package matching 'gitlab-runner' is available"

### ISSUE THREAD

**Issue by Listecky** [riemers/ansible-gitlab-runner#289]
Hello, I am trying to use this role but I am facing an issue i'cant pass (it is worth to mention that I am new to ansible so it may be a rookie mistake). 

Issue 1.

When I am running ansible-playbook I can observe that installation process is ongoing but at the end it returns message that it is missing gitlab-package.
I have a docker container from which I am running ansible.

The error I am getting:
```
  "msg": "No package matching 'gitlab-runner' is available"
```

Command I am using to run ansible-playbook:
```
 ansible-playbook -vvvv -I hosts.yml site.yml --check --extra-vars "ansible_user=USER ansible_password=PASSWORD ansible_become_password=PASSWORD"

```

main.yml with vars for riemers rule
```
gitlab_runner_coordinator_url: "gitlab-instance"
gitlab_runner_registration_token: "gitlab-token"
gitlab_runner_runners:
  - name: 'Example Docker GitLab Runner'
    executor: docker
    docker_image: 'test'
    tags:
      - node
```

site.yml:
```
- hosts: all
  become: true
  vars_files:
    - main.yml
  roles:
    - { role: riemers.gitlab-runner }

```

Dockerfile for a container hosting ansible:
```
FROM python:3.11

RUN python3 -m pip install ansible

RUN apt-get update
RUN apt-get install -y gnupg2
RUN apt-get install openssh-client
RUN apt-get install sshpass

RUN ansible-galaxy collection install community.general
RUN ansible-galaxy role install riemers.gitlab-runner

ENV ANSIBLE_HOST_KEY_CHECKING=False

``` 

Issue 2.

I also don't know what does it exactly mean, how should I provide a repository here?
```
gitlab_runner_skip_package_repo_install- Skip the APT or YUM repository installation (by default, false). You should provide a repository containing the needed packages before running this role.
```
