### ISSUE TITLE
Support for (pre,post)_*_script in gitlab-runner config

### ISSUE THREAD

**Issue by alexdelifer** [riemers/ansible-gitlab-runner#292]
Hey gang!

I was thinking of implementing the pre and post-scripts that gitlab-runner config supports.
https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section

Off the top of my head, I cannot recall if the `extra_configs` section would be capable of pulling this off, I seem to recall having some difficulties with it in the past.

There's some good intel over here too: https://dev.to/fkurz/gitlab-cicd-runner-clean-up-with-pre-build-scripts-4b0g on how to run cleanup scripts and what kinda scripts people might wanna run with these hooks.

I'll probably be able to tackle this this weekend, we have a need for this internally since we use a lot of Windows runners for UI tests, and frequently get left in broken states by less-than-ideal pipelines.

- pre_get_sources_script
- post_get_sources_script
- pre_build_script
- post_build_script

I was thinking something like
**Ansible Vars**
```
gitlab_runner_runners:
  - name: "{{ ansible_hostname|upper }}"
    executor: shell
    shell: powershell
    pre_build_script: powershell.exe -ExecutionPolicy Unrestricted -Command { $PRE_CLEAN_UP_SCRIPT } 
    post_build_script: powershell.exe -ExecutionPolicy Unrestricted -Command { $POST_CLEAN_UP_SCRIPT } 
```

**PRE_CLEAN_UP_SCRIPT**
```
taskkill /F /IM solidworks.exe
taskkill /F /IM myapp.exe
taskkill /F /IM otherbackgroundprocess.exe
remove-item -recurse -force C:\somestupidfolder
```

Users would set `$PRE_CLEAN_UP_SCRIPT` as Gitlab CI/CD variable, or as a CI job variable in their `gitlab-ci.yml`.

Very important to remember that these scripts are run in the context of the job, so if you're using docker, they're gonna be runner in the container, not on the host.

The example above is using windows shell executor so the reboot happens after the build.

And no, you can't just call reboot cause gitlab-runner will disconnect from the gitlab server and things go wrong quickly...

Please let me know if this is not a good idea for this project, or if I'm crazy and `extra_config` should be able to pull this off.

Cheers!
