### ISSUE TITLE
Set additional services is failing due to missing variable

### ISSUE THREAD

**Issue by kakawait** [riemers/ansible-gitlab-runner#294]
Hello

I've issue when using role without _services_

Here my `roles/requirements.yml`

```yml
- name: riemers.ansible-gitlab-runner
  src: https://github.com/riemers/ansible-gitlab-runner/archive/v2.0.3.tar.gz
```

I've also tried without the `src`, but I've added `src` after to be sure that I'm correctly fetching `2.0.3`

```bash
# ansible-galaxy install -r roles/requirements.yml --force
Starting galaxy role install process
- changing role riemers.ansible-gitlab-runner from v2.0.3 to unspecified
- downloading role from https://github.com/riemers/ansible-gitlab-runner/archive/v2.0.3.tar.gz
- extracting riemers.ansible-gitlab-runner to /root/.ansible/roles/riemers.ansible-gitlab-runner
- riemers.ansible-gitlab-runner was installed successfully
```

and I've 

```
TASK [riemers.ansible-gitlab-runner : conf[2/2]: runner[1/1]: Set additional services] *****************************************************************************************************
fatal: [gitlab.blabla]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.\n\nThe error appears to be in '/root/.ansible/roles/riemers.ansible-gitlab-runner/tasks/update-config-runner.yml': line 402, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#### [[runners.docker.services]] section ####\n- name:  \"{{ runn_name_prefix }} Set additional services\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

with following usage

```yml
- import_role:
     name: riemers.gitlab-runner
```

and variables

```yml
gitlab_runner_registration_token: THE_TOKEN
gitlab_runner_coordinator_url: https://gitlab.blaba/ci
gitlab_runner_windows_service_user: "domain\\user"
gitlab_runner_windows_service_password: password
# A list of runners to register and configure
gitlab_runner_runners:
    # The identifier of the runner.
  - name: "{{ inventory_hostname }} - shell"
    # set to 'absent' if you want to delete the runner. Defaults to 'present'.
    state: present
    # The executor used by the runner.
    executor: 'shell'
    shell: "{{ (ansible_system == 'Linux') | ternary('bash', 'powershell') }}"
    # Set maximum build log size in kilobytes.
    output_limit: 4096
    # Maximum number of jobs to run concurrently on this specific runner.
    # Defaults to 0, simply means don't limit.
    concurrent_specific: '5'
    # The tags assigned to the runner.
    tags:
      - "{{ inventory_hostname }}"
      - "shell"
      - "{{ (ansible_system == 'Linux') | ternary('linux', 'windows') }}"
    # Indicates whether this runner can pick jobs without tags.
    run_untagged: false
    # Docker privileged mode
    docker_privileged: false
    # Runner Locked. When a runner is locked, it cannot be assigned to other projects
    locked: 'false'
    # Custom environment variables injected to registration command
    env_vars: []
```

However it works if I'm downgrading to `v1.6.50`

May I missed something?

**Comment by guenhter** [comment]
What version of ansible do you use?

**Comment by kakawait** [comment]
> What version of ansible do you use?

I'm using 

```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
  ```

To be honest just used pre-packaged (`dnf`) version, but I could upgrade if required more recent version

**Comment by guenhter** [comment]
Can you run this two tasks to see if they pass on your system? (this is I think the issue on your end but I'm not 100% certain so that experiment would be helpful).

```
    - file:
        path: /tmp/foo1
        state: touch
    - blockinfile:
        dest: "/tmp/foo1"
        content: "{{ lookup('template', 'config.runners.docker.services.j2') if nondefinedvariable is defined }}"
        state: "{{ 'present' if nondefinedvariable is defined else 'absent' }}"
        marker: "# {mark} runners.docker.services"
        insertafter: EOF
      check_mode: no
```
