### ISSUE TITLE
Invalid config.toml for azure and gcp cache

### ISSUE THREAD

**Issue by philippwiesner** [riemers/ansible-gitlab-runner#295]
When configuring the gitlab-runner with a cache bucket from GCP or Azure an invalid cache config.toml is being generated. 

The following setting:
```
    cache_type: gcp
    cache_gcs_bucket_name: my_bucket
```

Produced the following config.toml:

```
name = "My Runner"
  limit = 0
  output_limit = 4096
  url = "https://gitlab.com"
  environment = []
  id = 27627360
  token = "<redacted>"
  token_obtained_at = 2023-11-15T13:42:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    [runners.cache.gcp]
      BucketName = "my_bucket"
    Type = "gcp"
    Path = "runner"
    Shared = true
    MaxUploadedArchiveSize = 0
  [runners.docker]
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    network_mtu = 0
```

The runner itself is working fine, however the cache is not working, as the config options for the GCP cache are not being read. Manually reordering those values before the `runners.docker` section will make the cache working again.

The same applies when trying to configure an azure cache. Only for s3 the config is generated correctly, but I don't understand why, as from the code in https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/update-config-runner.yml#L443 all 3 cache types are configured identically.

**Comment by NicolasIRAGNE** [comment]
hello, im quite a beginner to ansible so Im not sure Im doing everything correctly but I am currently having this problem

using
```
gitlab_runner_runners:
  - name: "{{ inventory_hostname }}"
    executor: docker
    cache_type: gcs
    cache_path: "gitlab-ci"
    cache_shared: true
    cache_gcs_bucket_name: "XXX"
    cache_gcs_credentials_file: "/etc/gitlab-runner/service-account.json"
    cache_dir: "/cache"
```
produces
```
  [runners.cache]
    [runners.cache.gcs]
      CredentialsFile = "/etc/gitlab-runner/service-account.json"
      BucketName = "shadow-runners-cache"
    Type = "gcs"
    Path = "gitlab-ci"
    Shared = true
    MaxUploadedArchiveSize = 0
```

which does not work. reordering manually fixes it.

I made sure I was using the correct version using
```sh
ansible-galaxy install git+https://github.com/riemers/ansible-gitlab-runner.git,2bbb712d2478a5cd18b155f5761dfce6d7665c7a
```
