### ISSUE TITLE
Support for docker tmpfs options

### ISSUE THREAD

**Issue by nicoklaus** [riemers/ansible-gitlab-runner#302]
Hello Together,

For a current use case we are using the option to mount a certain directory directly into the RAM as described in [https://docs.gitlab.com/runner/executors/docker.html#mount-a-directory-in-ram](https://docs.gitlab.com/runner/executors/docker.html#mount-a-directory-in-ram). 

After successful testing, I wanted to roll this out using the playbook, but always got an error when verifying the new configuration. 

My runner config looks like this:

```yaml
- name: "3-{{ ansible_fqdn }}"
    state: present
    concurrent_specific: "6"
    url: "{{ gitlab_url }}"
    token: "{{ token_p_g_77_0 }}"
    executor: "docker"
    docker_image: "nexus.example.com:18443/example:0.0.6"
    extra_configs:
      runners.docker:
        cpus: "20"
        volumes: ["/opt/build/gitlab-runner/embedded:/data:rw"]
      runners.docker.tmpfs:
        /var/lib/bitbake: "rw,exec"
```

When executing, the verification finally failed with the following error:

```
FATAL: toml: line 67 (last key \"runners.docker.tmpfs\"): expected '.' or '=', but got '/' instead\u001b[0;m \n"}
```

I was then able to trace this back to the tasks in https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/line-config-runner.yml and noticed that slashes were not taken into account here so far and therefore my configuration falls into the first task "Modify existing line", which has the consequence that the mount path is written without quotation marks and therefore does not represent a valid config. With the following adjustment I was able to insert the paths correctly.

```yaml
- name: "{{ line_name_prefix }} Modify existing line"
  lineinfile:
    path: "{{ temp_runner_config.path }}"
    insertafter: '\s+\[{{ section | regex_escape }}\]'
    regexp: '^(\s*)({{ line | regex_escape }}|{{ line | regex_escape }}) ='
    line: '{{ " " * (section.split(".")|length) }}{{ line }} = {{ gitlab_runner.extra_configs[section][line] | to_json }}'
  register: modified_config_line
# when: "not '.' in line"
  when: "not '.' in line and not '/' in line"

- name: "{{ line_name_prefix }} Modify existing line to_json"
  lineinfile:
    path: "{{ temp_runner_config.path }}"
    insertafter: '\s+\[{{ section | regex_escape }}\]'
    regexp: '^(\s*)({{ line | to_json | regex_escape }}|{{ line | regex_escape }}) ='
    line: '{{ " " * (section.split(".")|length) }}{{ line | to_json }} = {{ gitlab_runner.extra_configs[section][line] | to_json }}'
  register: modified_config_line
# when: "'.' in line"
  when: "'.' in line or '/' in line"
```
However, since I am not at all familiar with the regex used here, I am not sure whether this is the best variant.

Thank you so far for this great work.
