### ISSUE TITLE
Can't find package `gitlab-runner`

### ISSUE THREAD

**Issue by artinnok** [riemers/ansible-gitlab-runner#317]
Hi @riemers!

Thank you so much for amazing Ansible role - I believe it really helps.

I tried to use it with following playbook:
```yaml
- name: Setup
  hosts: staging
  become: true
  vars_files:
    - vars/vault.yaml
  tasks:
    - name: Install Gitlab Runner
      include_role:
        name: riemers.gitlab-runner
```

Managed node specs:
```sh
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

> uname -a
Linux staging-master 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I got this error:
```sh
TASK [riemers.gitlab-runner : (Debian) Unhold GitLab Runner version] ****************************************************************************************************
fatal: [142.93.161.200]: FAILED! => {"changed": false, "msg": "Failed to find package 'gitlab-runner' to perform selection 'install'."}
```

Also I tried to use Ubuntu 22 and got the same error.

I googled and found this [issue](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3067), maybe it can help for some workaround.

Feel free to ask questions.
Hope you can help me with this.

Thanks,
Artem.
