### ISSUE TITLE
Runtime owner and group for container setup

### ISSUE THREAD

**Issue by citypilgrim** [riemers/ansible-gitlab-runner#320]
When setting a `gitlab_runner_runner.cache_dir` config in `defaults/main.yml`. When using a docker executor, the task "Ensure directory permissions" fails because `gitlab_runner_runtime_{owner,group}` is set to `gitlab-runner`, when it should be `root` for docker executors.

Propose adding a task in `main-container.yml`:
```
- name: (Container) Set Runtime group and owner
  set_fact:
    gitlab_runner_runtime_owner: root
    gitlab_runner_runtime_group: root
```
