### ISSUE TITLE
Allow multiple runners to be registered

### ISSUE THREAD

**Issue by paulrbr-fl** [riemers/ansible-gitlab-runner#33]
Fow now only une runner can be registered with this playbook.

However `gitlab-runner` allows for any number of runners to be registered on the same machine.

**Comment by rgevaert** [comment]
@paulrbr-fl thanks for your work. I'm trying it but it seems not to work :-(
```
TASK [riemers.gitlab-runner : Register runner to GitLab] ***********************
task path: /Users/rgevaert/Vagrant/ubuntu18/provisioning/roles/riemers.gitlab-runner/tasks/register-runner.yml:2
fatal: [default]: FAILED! => {
    "msg": "The conditional check 'gitlab_runner.state == 'present'' failed. The error was: error while evaluating conditional (gitlab_runner.state == 'present'): 'dict object' has no attribute 'state'\n\nThe error appears to have been in '/Users/rgevaert/Vagrant/ubuntu18/provisioning/roles/riemers.gitlab-runner/tasks/register-runner.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Register runner to GitLab\n  ^ here\n"
}
```
```
gitlab_runner_docker_privileged: true
gitlab_runner_coordinator_url: 'xxx'
gitlab_runner_registration_token: 'xxxx'
gitlab_runner_runners:
  - name: 'vagrant-docker'
    executor: docker
    tags:
      - node
      - ruby
      - mysql
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # - "/cache"
  - name: 'vagrant-shell'
    executor: shell
    tags:
      - node
      - ruby
      - mysql
````

I also had to add `gitlab_runner_docker_privileged: true`
