### ISSUE TITLE
Failed to find package 'gitlab-runner' to perform selection 'install' debian 12 Vagrant

### ISSUE THREAD

**Issue by Minipada** [riemers/ansible-gitlab-runner#338]
Running a VM in virtualbox, I get a failure, using the latest commit [28404cc](https://github.com/riemers/ansible-gitlab-runner/commit/28404cc487752eca53dd8344c415dad1be02df83):

```bash
PLAY [Install Gitlab runner] ***************************************************

TASK [Gathering Facts] *********************************************************
ok: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : Load platform-specific variables] ****************
ok: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : Validate GitLab Runner configurations] ***********
included: /home/david.bensoussan/dev/infrastructure/servers/roles/riemers.gitlab-runner/tasks/validate-runner-config.yml for vm-gitlab-runner-bob => (item=bob-test)
included: /home/david.bensoussan/dev/infrastructure/servers/roles/riemers.gitlab-runner/tasks/validate-runner-config.yml for vm-gitlab-runner-bob => (item=wendy-test)

TASK [riemers.gitlab-runner : Check for deprecated settings: bob-test] *********
[WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: '{{ setting.name }}' not in
gitlab_runner
ok: [vm-gitlab-runner-bob] => (item=pre_clone_script)

TASK [riemers.gitlab-runner : Check for deprecated settings: wendy-test] *******
ok: [vm-gitlab-runner-bob] => (item=pre_clone_script)

TASK [riemers.gitlab-runner : Install Gitlab Runner (Container)] ***************
skipping: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : Install GitLab Runner (Unix)] ********************
[DEPRECATION WARNING]: Specifying a list of dictionaries for vars is deprecated
 in favor of specifying a dictionary. This feature will be removed in version 
2.18. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
included: /home/david.bensoussan/dev/infrastructure/servers/roles/riemers.gitlab-runner/tasks/main-unix.yml for vm-gitlab-runner-bob

TASK [riemers.gitlab-runner : Install GitLab Runner (Debian)] ******************
included: /home/david.bensoussan/dev/infrastructure/servers/roles/riemers.gitlab-runner/tasks/install-debian.yml for vm-gitlab-runner-bob

TASK [riemers.gitlab-runner : (Debian) Refresh package cache] ******************
ok: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : (Debian) Get Gitlab repository installation script] ***
ok: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : (Debian) Install Gitlab repository] **************
ok: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : (Debian) Update gitlab_runner_package_name] ******
ok: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : (Debian) Set gitlab_runner_package_name] *********
skipping: [vm-gitlab-runner-bob]

TASK [riemers.gitlab-runner : (Debian) Unhold GitLab Runner version] ***********
fatal: [vm-gitlab-runner-bob]: FAILED! => {"changed": false, "msg": "Failed to find package 'gitlab-runner' to perform selection 'install'."}
```

My config:
```yaml
gitlab_runner_package_version: 17.1.0
gitlab_runner_concurrent: 7
gitlab_runner_session_server_session_timeout: 10800
gitlab_runner_registration_token_type: "authentication-token"

gitlab_runner_coordinator_url: https://gitlab.com
gitlab_runner_no_log_secrets: false

# To be modified after review
gitlab_runner_runners:
  - name: "bob-test"
    executor: "docker"
    state: present
    token: TOKEN

  - name: "wendy-test"
    executor: "docker"
    state: present
    token: TOKEN
```

Any hint of what could be the reason?
