### ISSUE TITLE
Empty config after deploy

### ISSUE THREAD

**Issue by Heyzi** [riemers/ansible-gitlab-runner#359]
Can't get a working gitlab runner configuration, the final result is always empty. How can you figure out what's missing?
ansible and python:
```
ansible [core 2.15.13]
  config file = /builds/fu8xHyzy/0/devcloud-developer-service-rus/ide_team/devops/ansible-main/projects/gitlab-runner-installer/inventory/remote/ansible.cfg
  configured module search path = ['/home/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/ansible_collections
  executable location = /home/ansible/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/home/ansible/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```
my vars:
```
---
gitlab_runner_concurrent: 1
gitlab_runner_coordinator_url: "myurl"
gitlab_runner_registration_token: "mytoken"
gitlab_runner_registration_token_type: "registration-token"

gitlab_runner_sentry_dsn: ""

# GitLab TLS CA file
tls_ca_file: ""

gitlab_unregister_runner_executors_which_are_not_longer_configured: true

# default values for gitlab in container
gitlab_runner_container_install: true
gitlab_runner_container_image: gitlab-runner
gitlab_runner_container_tag: v17.7.0
gitlab_runner_container_name: gitlab-runner
gitlab_runner_container_mount_path: "/etc/gitlab-runner"
gitlab_runner_container_restart_policy: unless-stopped
gitlab_runner_container_latest_update: false
gitlab_runner_container_network: default

gitlab_runner_log_format: json
force_accept_gitlab_server_self_signed: true
gitlab_runner_show_config_diff: false
gitlab_runner_runners:
  - name: "Example Docker GitLab Runner"
    state: present
    executor: docker
    output_limit: 4096
    concurrent_specific: "1"
    docker_image: "dind:latest"
    tags:
      - test
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    docker_privileged: false
    docker_network_mode: bridge
    env_vars: []
    docker_services:
      - name: docker:20.10.12-dind
        command: ["--insecure-registry=10.0.0.0/24"]
    builds_dir: "/builds_dir"
    cache_dir: "/cache"
    feature_flags:
      - FF_TIMESTAMPS: true
      - FF_USE_FASTZIP: true
      - FF_LOG_IMAGES_CONFIGURED_FOR_JOB: true
```
but in the end, my configuration looks like this:
```
root@testserver:~# cat /etc/gitlab-runner/config.toml
log_level = "info"
log_format = "json"
check_interval = 0
  session_timeout = 1800
```

**Comment by guenhter** [comment]
Hi, it would be helpful to have the output of the Ansible run to see what steps were executed and ignored.

**Comment by starikov-aa** [comment]
I had the same problem. The authentication token (the token parameter) must be specified immediately in the Playbook. Otherwise, if the config (config.toml) of the runner is empty, Ansible will not create the settings at all. And if the config is created manually without specifying the token, Ansible will not register such a runner in Gitlab, since registration is only performed for new runners (determined by the name parameter), that is, those that are absent from the config (config.toml) at the time of starting Ansible.

My playbook:

```yaml
- name: Config Gitlab Runner
    hosts: all

    vars:
    ansible_python_interpreter: /usr/bin/python3
    gitlab_runner_package_version: 17.7.1-1
    gitlab_runner_concurrent: 1
    gitlab_runner_skip_package_repo_install: false
    gitlab_runner_registration_token_type: "authentication-token"
    gitlab_runner_config_update_mode: by_config_toml
    gitlab_runner_no_log_secrets: false
    gitlab_runner_coordinator_url: https://gitlab.site.com
    gitlab_runner_runners:
        - name: "{{ ansible_nodename }}"
            state: present
            token: "xxxxx"
            output_limit: 20000
            executor: docker
            run_untagged: false
            env_vars: ["GIT_SSL_NO_VERIFY=1"]
            docker_image: "alpine"
            docker_tlsverify: false
            docker_privileged: true
            docker_disable_cache: false
            docker_oom_kill_disable: false
            docker_shm_size: 0
            docker_volumes:
            - "/cache"
            docker_helper_image: "registry.site.com/gitlab-runner-helper:x86_64-v${CI_RUNNER_VERSION}"
            extra_configs:
            runners.docker:
                disable_entrypoint_overwrite: false
    roles:
    - riemers.gitlab-runner
```
