### ISSUE TITLE
Runner not created when docker_tlsverify: true under gitlab_runner_runners

### ISSUE THREAD

**Issue by didierlesage** [riemers/ansible-gitlab-runner#365]
When using a config like:

```
 gitlab_runner_runners:
      - name: "Central-Debug-1"
        executor: docker
        state: present
        docker_image: 'docker:stable'
        docker_tlsverify: true

```
in gitlab_runner_config_update_mode: by_registering 

the registration will fail, as the runner command is construct with the parameter` --docker-tlsverify: True` instead of `--docker-tlsverify`.
