### ISSUE TITLE
Fleeting based autoscale does not work

### ISSUE THREAD

**Issue by MartinGodzina** [riemers/ansible-gitlab-runner#372]
I'm trying to configure a GitLab runner using the `docker-autoscaler` executor with the Azure plugin. However, I couldn't find a native way to define `runners.autoscaler` settings within the role, so I placed them under `extra_configs`.

It seems there is an issue when assembling the final toml file. Specifically, the name field from plugin_config is incorrectly moved to the top level, causing misconfiguration. Below is a small example demonstrating the issue.

**Expected Behavior**
The name field should remain correctly nested under runners.autoscaler.plugin_config as defined in the runner configuration.

**Observed Behavior**
Instead, the name field gets incorrectly placed at the top level, leading to an invalid configuration.

**Reproduction Steps**

1. Use the following runner configuration:

```yml
gitlab_runner_runners:
  - name: "anyName"
    token: "anyToken"
    executor: "docker-autoscaler"
    docker_image: "alpine"
    concurrent_specific: "1"
    docker_volumes:
      - "/cache:/cache"
    extra_configs:
      runners.autoscaler:
        plugin: "azure"
        capacity_per_instance: 1
        max_use_count: 1
        max_instances: 10
      runners.autoscaler.plugin_config:
        name: "anyNamePlugin"
        subscription_id: "anySBID"
        resource_group_name: "anyRg"
```

2. After running the playbook, the generated toml file incorrectly looks like this:

```TOML
[[runners]]
    name = "anyNamePlugin" # Incorrect placement
  limit = 1
  output_limit = 4096
  url = "someUrl"
  environment = []
  id = 682
  token = "anyToken"
  token_obtained_at = 2025-03-04T08:58:04Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker-autoscaler"

  [runners.autoscaler]
    max_instances = 10
    max_use_count = 1
    capacity_per_instance = 1
    plugin = "azure"

    [runners.autoscaler.plugin_config]
      resource_group_name = "anyRg" #name should be here
      subscription_id = "anySBID"

```

Issue: The name field is incorrectly assigned to the runner instead of remaining inside runners.autoscaler.plugin_config.
There are probably more issues with the autoscale config but this is the first one i found during debugging this behavior.
