### ISSUE TITLE
Empty config and no registration after "container install"

### ISSUE THREAD

**Issue by spyesx** [riemers/ansible-gitlab-runner#382]
Starting from scratch and after many attempts at reading the code and other related issues I can't get a gitlab runner with Docker.

```shell
$ ansible --version
> ansible [core 2.17.9]
>   config file = /root/playbook/ansible.cfg
>   configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python3/dist-packages/ansible
>   ansible collection location = /root/playbook/collections
>   executable location = /usr/bin/ansible
>   python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
>   jinja version = 3.1.2
>   libyaml = True
```

## Obtain an authentication token for a Group

1. Gitlab.com > Group `X` > Build > Runners
2. New group runner
3. Tags: `arch-arm64`
     Run untagged jobs: `OK`
4. Create runner
5. Copy the token provided once only in `gitlab_runner_runners[0].token` bellow

## Prepare the playbook

File: `playbook.yml`

```yaml
---

- hosts: gitlab_runner
  gather_facts: false
  become: true
  roles:
    - name: riemers.gitlab-runner
 
```

## Configure some variables

File: `host_vars/server1/gitlab-runner.yml`

```yaml
---

# gitlab_runner_concurrent: "{{ ansible_processor_vcpus }}"
gitlab_runner_concurrent: "1"
gitlab_runner_check_interval: 15
gitlab_runner_coordinator_url: https://gitlab.com
gitlab_runner_registration_token: ""
gitlab_runner_registration_token_type: "authentication-token"
gitlab_runner_config_update_mode: by_config_toml

gitlab_runner_container_install: true
gitlab_runner_container_image: gitlab/gitlab-runner
gitlab_runner_container_tag: latest
gitlab_runner_container_name: gitlab-runner
gitlab_runner_container_mount_path: "/etc/gitlab-runner"
# gitlab_runner_container_mount_path: "/srv/{{ gitlab_runner_container_name }}"
gitlab_runner_container_restart_policy: unless-stopped
gitlab_runner_container_latest_update: false
gitlab_runner_container_network: default

gitlab_runner_show_config_diff: true

gitlab_runner_runners:
  - name: "{{ ansible_hostname }}"
    url: https://gitlab.com
    state: present
    executor: docker
    token: "glrt-REDACTED"
    output_limit: 4096
    concurrent_specific: "0"
    docker_image: "debian"
    tags:
      - arch-arm64
    run_untagged: true
    protected: false
    docker_privileged: false
    locked: false
    docker_network_mode: bridge
    env_vars: []
    docker_volumes:
      - "/cache"
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_registration_option: '--maximum-timeout=3600'
    extra_configs:
      runners.docker:
        memory: 512m
    #     allowed_images: ["ruby:*", "python:*", "php:*"]
    #   runners.docker.sysctls:
    #     net.ipv4.ip_forward: "1"

```

## Run the playbook

```bash
ansible-playbook playbook.yml
```

## Then read `config.toml`

```shell
# On the host
$ cat /etc/gitlab-runner/config.toml
> check_interval = 15
>  session_timeout = 1800

# From the container
$ docker exec -t gitlab-runner cat /etc/gitlab-runner/config.toml
> check_interval = 15
>   session_timeout = 1800
```

I can also confirm it from Gitlab UI:

![Image](https://github.com/user-attachments/assets/bd5d6086-b15a-49dd-8ec2-e2c0de24d968)

## Output of the Ansible run

```yaml

PLAY [gitlab_runner] ***********************************************************************************************************************************************************************************************************************************************************

TASK [riemers.gitlab-runner : Load platform-specific variables] ****************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Validate GitLab Runner configurations] ***********************************************************************************************************************************************************************************************************
included: /root/playbook/roles/riemers.gitlab-runner/tasks/validate-runner-config.yml for server1 => (item=server1)

TASK [riemers.gitlab-runner : Check for deprecated settings: server1] **********************************************************************************************************************************************************************************************************
ok: [server1] => (item=pre_clone_script)

TASK [riemers.gitlab-runner : Install Gitlab Runner (Container)] ***************************************************************************************************************************************************************************************************************
included: /root/playbook/roles/riemers.gitlab-runner/tasks/main-container.yml for server1

TASK [riemers.gitlab-runner : (Container) Pull Image from Registry] ************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : (Container) Define Container volume Path] ********************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : (Container) Delete runners which were removed in GitLab] *****************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : List configured runners as json] *****************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Initialze runner list] ***************************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Create list of configured runners] ***************************************************************************************************************************************************************************************************************
skipping: [server1] => (item={'arch': 'arm64', 'level': 'info', 'msg': 'Runtime platform', 'os': 'linux', 'pid': 7, 'revision': 'ef334dcc', 'time': '2025-04-11T12:58:35Z', 'version': '17.10.1'})
skipping: [server1] => (item={'ConfigFile': '/etc/gitlab-runner/config.toml', 'level': 'info', 'msg': 'Listing configured runners', 'time': '2025-04-11T12:58:35Z'})
skipping: [server1]

TASK [riemers.gitlab-runner : Print configured runners] ************************************************************************************************************************************************************************************************************************
ok: [server1] =>
  registered_gitlab_runner_names: []

TASK [riemers.gitlab-runner : (Container) Register GitLab Runner] **************************************************************************************************************************************************************************************************************
included: /root/playbook/roles/riemers.gitlab-runner/tasks/register-runner-container.yml for server1 => (item={'name': 'server1', 'url': 'https://gitlab.com', 'state': 'present', 'executor': 'docker', 'token': 'glrt-REDACTED', 'output_limit': 4096, 'concurrent_specific': '0', 'docker_image': 'debian', 'tags': ['arch-arm64'], 'run_untagged': True, 'protected': False, 'docker_privileged': False, 'locked': False, 'docker_network_mode': 'bridge', 'env_vars': [], 'docker_volumes': ['/cache', '/var/run/docker.sock:/var/run/docker.sock'], 'extra_registration_option': '--maximum-timeout=3600', 'extra_configs': {'runners.docker': {'memory': '512m'}}})

TASK [riemers.gitlab-runner : Construct the runner command without secrets] ****************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Check if the configuration has changed since the last run] ***************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : (Container) Unregister runner] *******************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : (Windows) Unregister runner] *********************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Unregister runner] *******************************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : List configured runners as json] *****************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Initialze runner list] ***************************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Create list of configured runners] ***************************************************************************************************************************************************************************************************************
skipping: [server1] => (item={'arch': 'arm64', 'level': 'info', 'msg': 'Runtime platform', 'os': 'linux', 'pid': 8, 'revision': 'ef334dcc', 'time': '2025-04-11T12:58:37Z', 'version': '17.10.1'})
skipping: [server1] => (item={'ConfigFile': '/etc/gitlab-runner/config.toml', 'level': 'info', 'msg': 'Listing configured runners', 'time': '2025-04-11T12:58:37Z'})
skipping: [server1]

TASK [riemers.gitlab-runner : Print configured runners] ************************************************************************************************************************************************************************************************************************
ok: [server1] =>
  registered_gitlab_runner_names: []

TASK [riemers.gitlab-runner : Register runner to GitLab] ***********************************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : Unregister runners which are not longer configured] **********************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Create .gitlab-runner dir] ***********************************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : Ensure config.toml exists] ***********************************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : Set concurrent option] ***************************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Set check_interval option] ***********************************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : Add listen_address to config] ********************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Add log_format to config] ************************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Add log_level to config] *************************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Add sentry dsn to config] ************************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Add session server listen_address to config] *****************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Add session server advertise_address to config] **************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Add session server session_timeout to config] ****************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : (Container) Configure GitLab Runner] *************************************************************************************************************************************************************************************************************
included: /root/playbook/roles/riemers.gitlab-runner/tasks/config-runners-container.yml for server1

TASK [riemers.gitlab-runner : Get existing config.toml] ************************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Get pre-existing runner configs] *****************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Create temporary directory] **********************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Write config section for each runner] ************************************************************************************************************************************************************************************************************
included: /root/playbook/roles/riemers.gitlab-runner/tasks/config-runner-container.yml for server1 => (item=check_interval = 15
  session_timeout = 1800
)

TASK [riemers.gitlab-runner : Create temporary file conf[1/1]:] ****************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Isolate runner configuration conf[1/1]:] *********************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Update config] ***********************************************************************************************************************************************************************************************************************************
skipping: [server1] => (item={'name': 'server1', 'url': 'https://gitlab.com', 'state': 'present', 'executor': 'docker', 'token': 'glrt-REDACTED', 'output_limit': 4096, 'concurrent_specific': '0', 'docker_image': 'debian', 'tags': ['arch-arm64'], 'run_untagged': True, 'protected': False, 'docker_privileged': False, 'locked': False, 'docker_network_mode': 'bridge', 'env_vars': [], 'docker_volumes': ['/cache', '/var/run/docker.sock:/var/run/docker.sock'], 'extra_registration_option': '--maximum-timeout=3600', 'extra_configs': {'runners.docker': {'memory': '512m'}}})
skipping: [server1]

TASK [riemers.gitlab-runner : Remove runner config conf[1/1]:] *****************************************************************************************************************************************************************************************************************
skipping: [server1] => (item={'name': 'server1', 'url': 'https://gitlab.com', 'state': 'present', 'executor': 'docker', 'token': 'glrt-REDACTED', 'output_limit': 4096, 'concurrent_specific': '0', 'docker_image': 'debian', 'tags': ['arch-arm64'], 'run_untagged': True, 'protected': False, 'docker_privileged': False, 'locked': False, 'docker_network_mode': 'bridge', 'env_vars': [], 'docker_volumes': ['/cache', '/var/run/docker.sock:/var/run/docker.sock'], 'extra_registration_option': '--maximum-timeout=3600', 'extra_configs': {'runners.docker': {'memory': '512m'}}})
skipping: [server1]

TASK [riemers.gitlab-runner : Assemble new config.toml] ************************************************************************************************************************************************************************************************************************
ok: [server1]

TASK [riemers.gitlab-runner : Remove temporary directory] **********************************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : (Container) Start the container] *****************************************************************************************************************************************************************************************************************
changed: [server1]

TASK [riemers.gitlab-runner : Install GitLab Runner (Unix)] ********************************************************************************************************************************************************************************************************************
skipping: [server1]

TASK [riemers.gitlab-runner : Install GitLab Runner (Windows)] *****************************************************************************************************************************************************************************************************************
skipping: [server1]

RUNNING HANDLER [riemers.gitlab-runner : Restart_gitlab_runner] ****************************************************************************************************************************************************************************************************************
skipping: [server1]

RUNNING HANDLER [riemers.gitlab-runner : Restart_gitlab_runner_macos] **********************************************************************************************************************************************************************************************************
skipping: [server1]

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
server1 : ok=33   changed=8    unreachable=0    failed=0    skipped=17   rescued=0    ignored=0
```
