### ISSUE TITLE
Unable to add feature_flags for windows runner

### ISSUE THREAD

**Issue by joannakotula** [riemers/ansible-gitlab-runner#384]
My ansible fragment:
```
- role: riemers.gitlab-runner
      gitlab_runner_concurrent: 1
      gitlab_runner_runners:
      - name: '{{ inventory_hostname }}'
        executor: shell
        shell: powershell
        token: "<token>"
        feature_flags:
          - FF_TIMESTAMPS
 ```

It doesn't add feature flags to `config.toml` file. It seems that it is implemented only in `update-config-runner.yml` and not in `update-config-runner-windows.yml`
