### ISSUE TITLE
Key 'runners.cache' has already been defined.

### ISSUE THREAD

**Issue by karlosss** [riemers/ansible-gitlab-runner#45]
My `gitlab_runner_runners` look as follows (pretty much like the example):
```
gitlab_runner_runners:
  - name: 'Example Docker GitLab Runner'
    executor: docker
    docker_image: 'alpine'
    tags:
      - nginx
      - python
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    extra_configs:
      runners.docker:
        memory: 512m
        allowed_images: ["nginx:*", "python:*"]
      runners.docker.sysctls:
        net.ipv4.ip_forward: "1"
```

When I run the playbook, I keep getting this error:
`FATAL: Near line 23 (last key parsed 'runners'): Key 'runners.cache' has already been defined.`

Any ideas what I am doing wrong? How can I recover from this? Or is it a bug?

Thanks a lot!
