### ISSUE TITLE
Default config.toml is not replaced by new one

### ISSUE THREAD

**Issue by jdecool** [riemers/ansible-gitlab-runner#69]
Hello, 

First of all thanks for your role and the work you did.

I've a problem when using it. The default `config.toml` is not replaced by the new configuration which is generated by Ansible.

When Ansible finish the work, on the server, I've two in the `/etc/gitlab-runner` directory.

```
root@buster:/etc/gitlab-runner# tree
.
├── config.toml
└── config.toml.6155.2019-10-06@07:50:13~

0 directories, 2 files
```

The first one `config.toml` contains the default content of the runner configuration:

```toml
concurrent = 2
check_interval = 0

[[runners]]
  name = "vagrant"
  limit = 1
  output_limit = 4096
  url = "https://gitlab.com/ci"
  token = "..."
  executor = "shell"
  [runners.docker]
    tls_verify = false
    disable_cache = false
    shm_size = 0
  [runners.cache]

  environment = []
[[runners]]
  name = "vagrant"
  limit = 1
  output_limit = 4096
  url = "https://gitlab.com/ci"
  token = "..."
  executor = "shell"
  [runners.cache]
  environment = []
```

Whereas the second one contains the configuration I want:

```toml
concurrent = 2
check_interval = 0

[[runners]]
  name = "vagrant"
  limit = 1
  output_limit = 4096
  url = "https://gitlab.com/ci"
  token = "..."
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
  [runners.cache]

[[runners]]
  name = "vagrant"
  limit = 1
  output_limit = 4096
  url = "https://gitlab.com/ci"
  token = "..."
  executor = "shell"
  [runners.cache]
```

During the process Ansible doesn't display any error.

For information, this my Ansible version information:

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jdecool/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Jul  9 2019, 16:43:02) [GCC 8.3.0]
```
