### ISSUE TITLE
miss placed docker_volumes option.

### ISSUE THREAD

**Issue by DisasteR** [riemers/ansible-gitlab-runner#72]
Hi,

Docker volumes a inserted in `[[runners]]` section instead of `[runners.docker]`

Regards,

**Comment by riemers** [comment]
Going away for a week, so don't have time to look into it now. Feel free to do a PR.

**Comment by hadret** [comment]
In the meantime, here's a workaround:

```
gitlab_runner_runners:
executor: docker
[...]
  extra_configs:
    runners.docker:
      volumes: []
```
