### ISSUE TITLE
Error "Assemble new config.toml" with executor "docker-machine"

### ISSUE THREAD

**Issue by notFloran** [riemers/ansible-gitlab-runner#85]
Hi, 

I have a runner with "docker+machine" as executor, when I execute my playbook it fails on `Assemble new config.toml`.

The issue seems to come from the generated config : 

```toml
  name = "my-gitlab-runner"
  executor = "docker+machine"
  ....
  [runners.docker+machine]
  environment = []
  [runners.docker]
    ...
  [runners.machine]
    ...
```

My config file done manually:

```toml
  name = "my-gitlab-runner"
  executor = "docker+machine"
  ....
  environment = []
  [runners.docker]
    ...
  [runners.machine]
    ...
```

My ansible config: 

```yaml
gitlab_runner_runners:
  - name: "my-gitlab-runner"
    executor: "docker+machine"
    docker_image: "alpine"
    extra_configs:
      runners.machine:
        MachineDriver: "digitalocean"
        ....
```

Any advice to fix that ?

**Comment by riemers** [comment]
Ah so runners+docker means you have them both? I don't think that is incorporated as of yet.

**Comment by notFloran** [comment]
> Ah so runners+docker means you have them both? I don't think that is incorporated as of yet.

Yes.

My config : 

```toml
[[runners]]
  name = "gitlab-runner-bastion"
  limit = 2
  url = "XXXX"
  token = "XXXXX"
  executor = "docker+machine"
  environment = ["COMPOSER_CACHE_DIR=/cache-ci/composer", "NPM_CONFIG_CACHE=/cache-ci/npm", "YARN_CACHE_FOLDER=/cache-ci/yarn", "PIP_CACHE_DIR=/cache-ci/pip"]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/cache-ci:/cache-ci:rw"]
    pull_policy = "if-not-present"
    shm_size = 0
  [runners.machine]
    IdleCount = 0
    IdleTime = 3600
    MachineDriver = "digitalocean"
    MachineName = "gitlab-runner-autoscale-%s"
    MachineOptions = ["engine-storage-driver=overlay2", "digitalocean-image=53551365", "digitalocean-ssh-user=root", "digitalocean-access-token=XXXXXXXXX", "digitalocean-region=fra1", "digitalocean-size=c-2", "digitalocean-private-networking", "digitalocean-tags=gitlab-ci-runner"]
    OffPeakTimezone = ""
    OffPeakIdleCount = 0
    OffPeakIdleTime = 0
```

**Comment by riemers** [comment]
https://github.com/riemers/ansible-gitlab-runner/blob/master/tasks/update-config-runner.yml if you look at that for example, you can see that the machine part is not yet there. I presume nobody used it before like that. Would need some adding and alterations, but i don't have those types of configs.

**Comment by richard-to** [comment]
I ran into this problem too. I got around it by removing this section from `ansible/roles_galaxy/riemers.gitlab-runner/tasks/update-config-runner.yml`

```
- name: Set runner executor section
  lineinfile:
    dest: "{{ temp_runner_config.path }}"
    regexp: '^\s*\[runners\.{{ gitlab_runner.executor|default("shell") }}\]'
    line: '  [runners.{{ gitlab_runner.executor|default("shell") }}]'
    state: present
    insertafter: '^\s*executor ='
    backrefs: no
  check_mode: no
  notify: restart_gitlab_runner
```

This line is what is creating the `[runners.docker+machine]`. This works in the `shell` and `docker` cases. But I guess it currently doesn't parse the `+` to create two sections one for `machine` and one for `docker`.

In this case I just removed it since the default seemed to create the necessary sections already. Although I haven't verified this yet.

Though it seems easy enough to parse the `docker` and `machine` out using a regex or something.
